channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - nomkl
  - geopandas
  - jupyter
  - palettable
  - r-base=3.4.1
  - r-ggplot2
  - r-obistools
  - r-robis
  - rise
  - rpy2
  - pip:
    - git+https://github.com/python-visualization/folium.git
